apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: nginx-ingress
    spec:
      type: LoadBalancer
      ports:
        - port: 80
          name: http
      selector:
        k8s-app: nginx-ingress-lb
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: nginx-ingress-controller
    spec:
      replicas: 1
      revisionHistoryLimit: 3
      template:
        metadata:
          labels:
            k8s-app: nginx-ingress-lb
        spec:
          terminationGracePeriodSeconds: 60
          containers:
            - name: nginx-ingress-controller
              # From https://github.com/kubernetes/contrib/blob/master/ingress/controllers/nginx/rc.yaml
              image: gcr.io/google_containers/nginx-ingress-controller:0.8.3
              imagePullPolicy: Always
              args:
                - /nginx-ingress-controller
                # Ingress controller redirects to the given server for any unknown subdomain, can be any but:
                # - Should serve a HTTP/404 on /
                # - Must serve a HTTP/200 on /healthz
                - --default-backend-service=default/helloworld3-service
              # Use downward API
              env:
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              ports:
                - containerPort: 80
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: ingress
      annotations:
        # This tells to only use the Nginx Ingress Controller
        # and avoids the creation on a Global LoadBalancer on GKE.
        kubernetes.io/ingress.class: "nginx"
    spec:
      # tls:
      #   - secretName: tls-certificate
      #     # List of hosts supported by this certificate:
      #     hosts:
      #       - richardknop.com
      #       - foo.example.com
      rules:
        - host: richardknop.com
          http:
            paths:
              - path: /
                backend:
                  serviceName: helloworld1-service
                  servicePort: 80
              - path: /foo
                backend:
                  serviceName: helloworld2-service
                  servicePort: 80
              - path: /bar
                backend:
                  serviceName: helloworld3-service
                  servicePort: 80
        - host: foo.richardknop.com
          http:
            paths:
              - path: /
                backend:
                  serviceName: helloworld2-service
                  servicePort: 80
        - host: bar.richardknop.com
          http:
            paths:
              - path: /
                backend:
                  serviceName: helloworld3-service
                  servicePort: 80

